const RAFLATAC = "RAFLATAC";
const RAFLATAC_MATTE = "RAFLATAC_MATTE";
const RAFLATAC_GLOSS = "RAFLATAC_GLOSS";
const RAFLATAC_FOIL = "RAFLATAC_FOIL";
const RITRAMA_MATTE = "RITRAMA_MATTE";
const RITRAMA_GLOSS = "RITRAMA_GLOSS";
const RITRAMA_COATED = "RITRAMA_COATED";
const TRANSPARENT = "TRANSPARED";
const TRANSPARENT_MATTE = "TRANSPARENT_MATTE";
const TRANSPARENT_WHITE = "TRANSPARENT_WHITE";
const TRANSPARENT_FOIL = "TRANSPARENT_FOIL";
const VINE = "VINE";
const PET = "PET";

export {
  RAFLATAC,
  RAFLATAC_MATTE,
  RAFLATAC_GLOSS,
  RAFLATAC_FOIL,
  RITRAMA_MATTE,
  RITRAMA_GLOSS,
  RITRAMA_COATED,
  TRANSPARENT,
  TRANSPARENT_MATTE,
  TRANSPARENT_WHITE,
  TRANSPARENT_FOIL,
  VINE,
  PET,
};
